<a href="https://colab.research.google.com/github/hazra-kerubo/DescriptiveAnalysis/blob/main/Model_Deployment_Grp_2_Streamlit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
# Plotting Confusion matrix results
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score



In [ ]:
# Loading detect dataset

detect_df = pd.read_csv('/content/detect_dataset.csv')

# Loading class_df dataset

class_df = pd.read_csv('/content/classData.csv')

In [ ]:
detect_df = detect_df.drop(detect_df[['Unnamed: 7', 'Unnamed: 8']],axis=1)
detect_df.sample(5)

Output (S)          Ia          Ib         Ic        Va        Vb  \
2405           0  -58.249132   -0.610827  55.231011  0.188352 -0.593169   
4413           0  -57.122653    1.093783  58.707365  0.254819 -0.600891   
5938           0  -61.089452   73.642305 -10.239339 -0.413997 -0.177073   
2753           1  853.561083 -288.209949  24.704700  0.027074 -0.336386   
7625           0  -80.738728   40.311144  42.352363  0.239471 -0.531522   

            Vc  
2405  0.404817  
4413  0.346073  
5938  0.591070  
2753  0.309312  
7625  0.292051

In [ ]:
# Defining target and predictors in detect_df

detect_X = detect_df.drop(columns=['Output (S)'],axis=1)
detect_cols = detect_X.columns

detect_y = detect_df['Output (S)']

#detect_y = detect_df.iloc[:,0]

In [ ]:
# Feature Scaling
# ---

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(detect_X)

detect_X = pd.DataFrame(X_scaled, columns= detect_cols)

In [ ]:
# Split the detect dataset into train and test sets

X_train, X_test, y_train, y_test = train_test_split(detect_X, detect_y, test_size=0.2, random_state=0)

In [ ]:
# Building the svm model using rbf kernel
polyclassifier = SVC(kernel='poly', degree=3, gamma=5,C=5)
# Training the model using the training set
polyclassifier.fit(X_train, y_train)

# making prediction
y_pred_poly = polyclassifier.predict(X_test)

# Model Evaluation
print( accuracy_score(y_test, y_pred_poly))

0.9933361099541858


In [ ]:
# Checking the confusion matrix
print(confusion_matrix(y_test,y_pred_poly))

[[1323    2]
 [  14 1062]]


###Predictive System _detect

In [ ]:
input_data = (-170.472196,	9.219613,	161.252583,	0.05449,	-0.659921,	0.605431)
#input_data= (-122.235754,	6.168667,	116.067087,	0.10200,	-0.628612,	0.526202)
#input_data= (34.915928,	-763.685747,	731.186927,	-0.073894,	0.010801,	0.063093)
#input_data= (-353.742509,	877.841978,	-524.101733,	0.026485,	0.015394,	-0.041879)


In [ ]:
# Changing input_data to numpy array
input_data_as_numpy_array=np.asarray(input_data)

In [ ]:
# reshape the array as we are predicting for one instance
input_data_reshaped =  input_data_as_numpy_array.reshape(-1,1)

In [ ]:
input_data_reshaped

array([[-1.70472196e+02],
       [ 9.21961300e+00],
       [ 1.61252583e+02],
       [ 5.44900000e-02],
       [-6.59921000e-01],
       [ 6.05431000e-01]])

In [ ]:
#prediction = polyclassifier.predict(input_data_reshaped)
#print(prediction)

In [ ]:
#prediction = polyclassifier.predict(input_data_reshaped)
#print(prediction)

#if(prediction[0]==0):
#  print('Line is not faulty')
#else:
#  print('Line is faulty')

In [ ]:
import pickle

In [ ]:
import pickle

filename = 'trained_model.sav'
pickle.dump(polyclassifier, open(filename, 'wb'))

In [ ]:
# loading the saved model
loaded_model = pickle.load(open('trained_model.sav', 'rb'))

In [ ]:
input_data = (-170.472196,	9.219613,	161.252583,	0.05449,	-0.659921,	0.605431)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The line not Faulty')
else:
  print('The line is Faulty')


[1]
The line is Faulty


In [ ]:
!pip install networkx
!pip install streamlit
import streamlit as st

In [ ]:
import numpy as np
import pickle
import streamlit as st


# loading the saved model
loaded_model = pickle.load(open('/content/trained_model.sav', 'rb'))



# creating a function for Prediction

def fault_prediction(input_data):


    
# changing the input_data to numpy array
 input_data_as_numpy_array = np.asarray(input_data)

    # reshape the array as we are predicting for one instance
 input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

 prediction = loaded_model.predict(input_data_reshaped)
 print(prediction)

 if (prediction[0] == 0):
   return 'The line is not faulty'
 else:
   return 'The line is faulty'   
  
def main():
    
    
    # giving a title
 st.title('Fault Prediction Web App')
    
    
    # getting the input data from the user
    
    
 Ia = st.text_input('Input Current Value for phase A')
 Ib = st.text_input('Input Current Value for phase B')
 Ic = st.text_input('Input Current Value for phase C')
 Va = st.text_input('Input Voltage Value for phase A')
 Vb = st.text_input('Input Voltage Value for phase B')
 Vc = st.text_input('Input Voltage Value for phase C')
    
    
    # code for Prediction
 fault_status = ''
 
    
    # creating a button for Prediction
    
 if st.button('Fault Check Result'):
   fault_status = fault_prediction([Ia, Ib, Ic, Va, Vb, Vc])

             
 st.success(fault_status)
    
    
if __name__ == '__main__':
  main()

2022-03-26 10:40:40.516 
  command:

    streamlit run /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py [ARGUMENTS]


In [ ]:
!streamlit run app.py &>/dev/null&

In [ ]:
!pip -q install pyngrok
from pyngrok import ngrok 
!ngrok authtoken [Enter your authtoken here]
!nohup streamlit run app.py & 

NAME:
   authtoken - save authtoken to configuration file

USAGE:
   ngrok authtoken [command options] [arguments...]

DESCRIPTION:
   The authtoken command modifies your configuration file to include
   the specified authtoken. By default, this configuration file is located
   at $HOME/.ngrok2/ngrok.yml

   The ngrok.com service requires that you sign up for an account to use
   many advanced service features. In order to associate your client with
   an account, it must pass a secret token to the ngrok.com service when it
   starts up. Instead of passing this authtoken on every invocation, you may
   use this command to save it into your configuration file so that your
   client always authenticates you properly.

EXAMPLE:
    ngrok authtoken BDZIXnhJt2HNWLXyQ5PM_qCaBq0W2sNFcCa0rfTZd

OPTIONS:
   --config 		save in this config file, default: ~/.ngrok2/ngrok.yml
   --log "false"	path to log file, 'stdout', 'stderr' or 'false'
   --log-format "term"	log record format: 'term', 'logfmt',

In [ ]:
!pip install pyngrok==4.1.1

In [ ]:
#public_url = ngrok.connect(port=‘80’)
public_url = ngrok.connect('8501')
public_url

2022-03-26 10:40:49.250 ngrok process starting: 693
2022-03-26 10:40:49.267 t=2022-03-26T10:40:49+0000 lvl=info msg="no configuration paths supplied"

2022-03-26 10:40:49.272 t=2022-03-26T10:40:49+0000 lvl=info msg="using configuration at default config path" path=/root/.ngrok2/ngrok.yml

2022-03-26 10:40:49.273 t=2022-03-26T10:40:49+0000 lvl=info msg="open config file" path=/root/.ngrok2/ngrok.yml err=nil

2022-03-26 10:40:49.274 t=2022-03-26T10:40:49+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040

2022-03-26 10:40:49.586 t=2022-03-26T10:40:49+0000 lvl=info msg="tunnel session started" obj=tunnels.session

2022-03-26 10:40:49.587 t=2022-03-26T10:40:49+0000 lvl=info msg="client session established" obj=csess id=9425234677ef

2022-03-26 10:40:49.597 ngrok process has started: http://127.0.0.1:4040
2022-03-26 10:40:49.601 t=2022-03-26T10:40:49+0000 lvl=info msg=start pg=/api/tunnels id=575fe45c9d12aae1

2022-03-26 10:40:49.605 t=2022-03-26T10:40:49+0000 lvl=info msg

'http://6646-34-91-147-169.ngrok.io'

2022-03-26 10:40:49.844 t=2022-03-26T10:40:49+0000 lvl=info msg="started tunnel" obj=tunnels name=http-8501-c8a88f72-706a-4da9-8653-623b5871c73b addr=http://localhost:8501 url=https://6646-34-91-147-169.ngrok.io

2022-03-26 10:40:49.846 t=2022-03-26T10:40:49+0000 lvl=info msg=end pg=/api/tunnels id=c976f67a79c65565 status=201 dur=240.472482ms



#Classification Dataset - Deployment 

In [ ]:
# Creating column 'fault_types'
class_df['fault_types'] = class_df['G'].astype('str') + class_df['C'].astype('str') + class_df['B'].astype('str') + class_df['A'].astype('str')
class_df.sample(4)

G  C  B  A          Ia          Ib          Ic        Va        Vb  \
5780  0  0  0  0  -53.353433   98.297106  -48.401301 -0.530159  0.003488   
217   1  0  0  1  839.080654   64.326698  -13.425958 -0.170489 -0.027766   
3245  0  1  1  0  -41.716369 -333.765344  377.727669 -0.504371 -0.036645   
2025  1  0  1  1 -520.725142 -342.284192  -53.077623 -0.041832  0.364258   

            Vc fault_types  
5780  0.526671        0000  
217   0.198256        1001  
3245  0.541017        0110  
2025 -0.322426        1011

In [ ]:
class_df.columns

Index(['G', 'C', 'B', 'A', 'Ia', 'Ib', 'Ic', 'Va', 'Vb', 'Vc', 'fault_types'], dtype='object')

In [ ]:
clf_X = class_df.drop(columns=['G','C','B','A','fault_types'],axis=1)
clf_cols = clf_X.columns

new_class_y = class_df['fault_types']

#clf_y = class_df.iloc[:,0:4]

In [ ]:
# Scaling data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
class_scaled = scaler.fit_transform(clf_X)

clf_X = pd.DataFrame(class_scaled, columns= clf_cols)

In [ ]:
from sklearn.model_selection import train_test_split

class_train_X, class_test_X, class_train_y, class_test_y = train_test_split(clf_X,new_class_y,test_size=0.2,random_state=0)

In [ ]:
new_class_y.unique()

array(['1001', '1011', '0110', '0111', '1111', '0000'], dtype=object)

In [ ]:
# Transforming y_train and y_test
#class_y_train = np.array([class_train_y['G']+class_train_y['A']+class_train_y['B']+class_train_y['C']])
#class_y_train= class_y_train.transpose().ravel()

#class_y_test = np.array([class_test_y['G']+class_test_y['A']+class_test_y['B']+class_test_y['C']])
#class_y_test= class_y_test.transpose().ravel()

In [ ]:
#[G C B A]
#[0 0 0 0] -> No fault 
#[1 0 0 1] -> LG fault(Between Phase A and ground)
#[0 1 1 0] -> LL fault(Between Phase A and Phase B)
#[1 0 1 1] -> LLG Fault(Between Phases A,B and ground)
#[0 1 1 1] -> LLL Fault(Between all three phases)
#[1 1 1 1] -> LLLG fault(Three phase symmetrical fault)

###KNN

In [ ]:
# Train the model with KNN classifier
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5)
classifier_knn.fit(class_train_X, class_train_y)

KNeighborsClassifier()

In [ ]:
#Making predictions
y_pred_knn = classifier_knn.predict(class_test_X)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

clf_report = classification_report(class_test_y, y_pred_knn)
print("Classification Report:",)
print (clf_report)
model_accuracy = accuracy_score(class_test_y,y_pred_knn)
print("Accuracy:",model_accuracy)

Classification Report:
              precision    recall  f1-score   support

        0000       1.00      1.00      1.00       469
        0110       1.00      1.00      1.00       197
        0111       0.33      0.33      0.33       223
        1001       0.95      1.00      0.98       221
        1011       0.97      0.95      0.96       219
        1111       0.37      0.35      0.36       244

    accuracy                           0.80      1573
   macro avg       0.77      0.77      0.77      1573
weighted avg       0.80      0.80      0.80      1573

Accuracy: 0.7972027972027972


##Polynomial Fn

In [ ]:
# Building the svm model using rbf kernel
polynomial_clf = SVC(kernel='poly', degree=3, gamma=10,C=10)
# Training the model using the training set
polynomial_clf.fit(class_train_X, class_train_y)

# making prediction
class_y_pred = polynomial_clf.predict(class_test_X)

# Model Evaluation
# Checking the confusion matrix
print('Confusion_Matrix:')
print(confusion_matrix(class_test_y,class_y_pred))
print('*******************')
print('Model_Accuracy:') 
print(accuracy_score(class_test_y, class_y_pred))

Confusion_Matrix:
[[469   0   0   0   0   0]
 [  0 197   0   0   0   0]
 [  0   0 221   0   0   2]
 [  0   0   0 221   0   0]
 [  0   0   1   1 217   0]
 [  0   0  48   0   0 196]]
*******************
Model_Accuracy:
0.9669421487603306


##Predictive System

###Polynomial fn

In [ ]:
import pickle

filename = 'polyn_model.sav'
pickle.dump(polynomial_clf, open(filename, 'wb'))

# loading the saved model
polyn_loaded_model = pickle.load(open('polyn_model.sav', 'rb'))

In [ ]:
#input_data1 = (-206.355772,	-656.867517,	865.389355,	-0.037551,	0.010533,	0.027018)
#input_data1 = (54.376385,	-183.788626,	132.004850,	0.423327,	0.041784,	-0.465111)
input_data1 = (-151.291812,	-9.677452,	85.800162,	0.400750,	-0.132935,	-0.267815)
# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data1)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = polynomial_clf.predict(input_data_reshaped)
print(prediction)
if(prediction=='1011'):
  print('LLG')
elif(prediction=='1111'):
  print('LLLG')
elif(prediction=='0110'):
  print('LL')
elif(prediction=='0000'):
  print('NF')
elif(prediction=='0111'):
  print('LLL')
elif(prediction=='1001'):
  print('LG')

else:
  print('Undefined fault')  

['1011']
LLG


In [ ]:
#input_data4 = (-206.355772,	-656.867517,	865.389355,	-0.037551,	0.010533,	0.027018)
input_data = (54.376385,	-183.788626,	132.004850,	0.423327,	0.041784,	-0.465111)
#input_data = (-151.291812,	-9.677452,	85.800162,	0.400750,	-0.132935,	-0.267815)
# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = polynomial_clf.predict(input_data_reshaped)
print(prediction)

if(prediction=='1011'):
  print('The fault type is: LLG Fault')
elif(prediction=='1111'):
  print('The fault type is: LLLG Fault')
elif(prediction=='0110'):
  print('The fault type is: LL Fault')
elif(prediction=='0000'):
  print('No fault')
elif(prediction=='0111'):
  print('The fault type is: LLL')
elif(prediction=='1001'):
  print('The fault type is: LG')

else:
  print('Undefined fault')   

['1111']
The fault type is: LLLG Fault


In [ ]:
import numpy as np
import pickle
import streamlit as st


# loading the saved model
polyn_loaded_model = pickle.load(open('/content/polyn_model.sav', 'rb'))


# creating a function for Prediction
@st.cache

def fault_class_prediction(input_data):


  # changing the input_data to numpy array
 input_data_as_numpy_array = np.asarray(input_data)
  
# reshape the array as we are predicting for one instance

 input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)


prediction = polyn_loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction=='1011'):
  print('The fault type is: LLG Fault')
elif(prediction=='1111'):
  print('The fault type is: LLLG Fault')
elif(prediction=='0110'):
  print('The fault type is: LL Fault')
elif(prediction=='0000'):
  print('No fault')
elif(prediction=='0111'):
  print('The fault type is: LLL')
elif(prediction=='1001'):
  print('The fault type is: LG')

else:
  print('Undefined fault')

  
def main():
    
    
    # giving a title
 st.title('Fault Type Prediction Web App')
    
    
    # getting the input data from the user
    
    
 Ia = st.text_input('Input Current Value for phase A')
 Ib = st.text_input('Input Current Value for phase B')
 Ic = st.text_input('Input Current Value for phase C')
 Va = st.text_input('Input Voltage Value for phase A')
 Vb = st.text_input('Input Voltage Value for phase B')
 Vc = st.text_input('Input Voltage Value for phase C')
    
    
    # code for Prediction
 fault_class = ''

    
    # creating a button for Prediction
    
 if st.button('Fault Type Result'):
   fault_class = fault_class_prediction([Ia, Ib, Ic, Va, Vb, Vc])

             
 st.success(fault_class)
    
    
if __name__ == '__main__':
  main()

['1011']
The fault type is: LLG Fault


###KNN

In [ ]:
import pickle

filename = 'knn_model.sav'
pickle.dump(classifier_knn, open(filename, 'wb'))

# loading the saved model
knn_loaded_model = pickle.load(open('knn_model.sav', 'rb'))

In [ ]:
input_data1 = (-151.291812,	-9.677452,	85.800162,	0.400750,	-0.132935,	-0.267815)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data1)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = knn_loaded_model.predict(input_data_reshaped)
print(prediction)

['1111']


In [ ]:
input_data1 = (-703.090202,	-85.622904,	-44.015875,	-0.038023,	0.376207,	-0.338184)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data1)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction2 = knn_loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction2[0]=='0000'):
  print('No faulty')
  if(prediction2[1]=='1001'):
    print('LG faulty')
    if(prediction2[2]=='0110'):
      print('LL faulty')
      if(prediction2[3]=='1011'):
        print('LLG')
        if(prediction2[4]=='0111'):
          print('LLL')
          if(prediction2[5]=='1111'):
            print('LLLG')
else:
  print('Undefined fault') 

['1111']
Undefined fault


In [ ]:
class_df.fault_types.unique()

array(['1001', '1011', '0110', '0111', '1111', '0000'], dtype=object)

In [ ]:
input_data1 = (19.611097,	-27.203132,	4.150914,	0.571750,	-0.139266,	-0.432484)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data1)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction2 = knn_loaded_model.predict(input_data_reshaped)
print(prediction2)

if prediction2==['0000']:
  print('No faulty')
  if prediction2=='1001':
    print('LG faulty')
  elif prediction2=='0110':
    print('LL faulty')
  elif prediction2=='1011':
    print('LLG')
  elif prediction2=='0111':
    print('LLL')
  elif prediction2=='1111':
    print('LLLG')
else:
  print('Could not find true fault expression') 

['1111']
Could not find true fault expression


In [ ]:
if(prediction2[0]=='0000'):
  print('No faulty')
elif(prediction2[1]=='1001'):
  print('LG faulty')
elif(prediction2[2]=='0110'):
  print('LL faulty')
elif(prediction2[3]=='1011'):
  print('LLG')
elif(prediction2[4]=='0111'):
  print('LLL')
elif(prediction2[5]=='1111'):
  print('LLLG')
else:
  print('Undefined fault') 

In [ ]:
if(prediction2[0]=='0000'):
  print('No faulty')
  if(prediction2[1]=='1001'):
    print('LG faulty')
    if(prediction2[2]=='0110'):
      print('LL faulty')
      if(prediction2[3]=='1011'):
        print('LLG')
        if(prediction2[4]=='0111'):
          print('LLL')
          if(prediction2[5]=='1111'):
            print('LLLG')
else:
  print('Undefined fault')  


